name: CI/CD Pipeline for Docker to EC2

on:
  push:
    branches:
      - 'feature/*'  # Trigger pipeline ketika ada push ke branch main
  pull_request:
    branches:
      - main  # Trigger pipeline saat pull request dibuat ke branch main

jobs:
  ci:
    runs-on: ubuntu-20.04
    steps:
      # Step 1: Checkout kode
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Login ke Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build Docker image
      - name: Build Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            salimburdah/ntx-app:latest
      
      # salimburdah/${{ secrets.DOCKER_IMAGE_NAME }}:latest
      # # Step 5: Run tests (Opsional, jika Anda punya test)
      # - name: Run tests (Optional)
      #   run: |
      #     docker run --rm ${{ secrets.DOCKER_IMAGE_NAME }}:latest npm test

  cd:
    runs-on: ubuntu-20.04
    needs: ci  # Hanya dijalankan setelah job ci selesai

    steps:
      # Step 6: Setup SSH untuk EC2
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_PRIVATE_KEY }}

      # Step 7: Pull image dari Docker Hub ke EC2 dan jalankan
      - name: SSH to EC2 and Deploy Docker container
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST_1 }} << 'EOF'
            
            # Memeriksa apakah Docker sudah terinstal
            if ! command -v docker &> /dev/null; then
              echo "Docker tidak ditemukan, menginstal Docker..."

              # Instal Docker
              sudo apt update
              sudo apt install -y apt-transport-https ca-certificates curl software-properties-common
              curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
              echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
              sudo apt update
              sudo apt install -y docker-ce docker-ce-cli containerd.io
            fi

            # Pull Docker image terbaru
            sudo docker pull salimburdah/ntx-app:latest

            # Hentikan dan hapus container lama (jika ada)
            sudo docker stop ntx-app || true
            sudo docker rm ntx-app || true

            # Jalankan container baru
            sudo docker run -d --name ntx-app -p 3000:3000 salimburdah/ntx-app:latest
          EOF

      - name: SSH to EC2 Instance 2 and Deploy Docker container
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST_2 }} << 'EOF'
            # Memeriksa apakah Docker sudah terinstal
            if ! command -v docker &> /dev/null; then
              echo "Docker tidak ditemukan, menginstal Docker..."
              
              # Instal Docker
              sudo apt update
              sudo apt install -y apt-transport-https ca-certificates curl software-properties-common
              curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
              echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
              sudo apt update
              sudo apt install -y docker-ce docker-ce-cli containerd.io
            fi

            # Pull the latest Docker image
            sudo docker pull salimburdah/ntx-app:latest

            # Stop and remove the old container (if exists)
            sudo docker stop ntx-app || true
            sudo docker rm ntx-app || true

            # Run the new container
            sudo docker run -d --name ntx-app -p 3000:3000 salimburdah/ntx-app:latest
          EOF
